export const CartActionTypes = {
    TOGGLE_CART_VIEW: 'TOGGLE_CART_VIEW',
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CARD: 'CLEAR_ITEM_FROM_CARD',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLOSE_CART_VIEW: 'CLOSE_CART_VIEW'

}